services:
  - type: web
    name: nams-evoting-backend
    env: node
    buildCommand: |
      cd backend
      npm install
    startCommand: cd backend && node server.js
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production